variables:
    IMAGE_NAME: docker push akaax/ashraf_repo
    IMAGE_TAG: python

run_tests:
    image: python:3
    before_script:
        - apt-get update
        - apt-get install -y firefox-esr
        - apt-get install -y xvfb
        - pip3 install robotframework robotframework-seleniumlibrary  --break-system-packages
    script:
        - python3 tests/main.py

build_image:
    image: docker
    services:
        - docker:20.10.16-dind
    before_script:
        - docker login -u $REGESTRY_USER -p $REGESTRY_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG ./client
        - docker push $IMAGE_NAME:$IMAGE_TAG