version: '3.8'

services:
  app:
    container_name: docker_react_c
    image: store_app
    build:
      context: ./client
    ports:
      - 8080:80
  tests:
    container_name: tests_c
    image: tests_i
    build:
      context: ./tests